version: 2
updates:
  # Update root npm dependencies - JS/TS
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update Docker dependencies in containers directory
  - package-ecosystem: "docker"
    directory: "/containers"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update Core package dependencies - JS/TS
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

# Update Functions package dependencies - JS/TS
  - package-ecosystem: "npm"
    directory: "/packages/functions"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

# Update WWW package dependencies - JS/TS
  - package-ecosystem: "npm"
    directory: "/packages/www"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

# Update Zero package dependencies - JS/TS
  - package-ecosystem: "npm"
    directory: "/packages/zero"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update Steam Nuget package dependencies - C#
  - package-ecosystem: "nuget"
    directory: "/packages/steam"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update Nestri-server package dependencies - Rust
  - package-ecosystem: "cargo"
    directory: "/packages/server"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update Relay package dependencies - Go
  - package-ecosystem: "gomod"
    directory: "/packages/relay"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

# Update Maitred package dependencies - Go
  - package-ecosystem: "gomod"
    directory: "/packages/maitred"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update WWW app dependencies - JS/TS
  - package-ecosystem: "npm"
    directory: "/apps/www"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

# Update Docs app dependencies - JS/TS
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"