version: 2
updates:
  # Update root npm dependencies (if you have a root package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update Docker dependencies in containers directory
  - package-ecosystem: "docker"
    directory: "/containers"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update individual package dependencies - JavaScript/TypeScript
  - package-ecosystem: "npm"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update individual package dependencies - C#
  - package-ecosystem: "nuget"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update individual package dependencies - Rust
  - package-ecosystem: "cargo"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update individual package dependencies - Go
  - package-ecosystem: "gomod"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Update individual app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"