// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoTimestampEntry {
    #[prost(string, tag="1")]
    pub stage: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoLatencyTracker {
    #[prost(string, tag="1")]
    pub sequence_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub timestamps: ::prost::alloc::vec::Vec<ProtoTimestampEntry>,
}
// Mouse messages 

/// MouseMove message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProtoMouseMove {
    #[prost(int32, tag="1")]
    pub x: i32,
    #[prost(int32, tag="2")]
    pub y: i32,
}
/// MouseMoveAbs message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProtoMouseMoveAbs {
    #[prost(int32, tag="1")]
    pub x: i32,
    #[prost(int32, tag="2")]
    pub y: i32,
}
/// MouseWheel message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProtoMouseWheel {
    #[prost(int32, tag="1")]
    pub x: i32,
    #[prost(int32, tag="2")]
    pub y: i32,
}
/// MouseKeyDown message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProtoMouseKeyDown {
    #[prost(int32, tag="1")]
    pub key: i32,
}
/// MouseKeyUp message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProtoMouseKeyUp {
    #[prost(int32, tag="1")]
    pub key: i32,
}
// Keyboard messages 

/// KeyDown message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProtoKeyDown {
    #[prost(int32, tag="1")]
    pub key: i32,
}
/// KeyUp message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProtoKeyUp {
    #[prost(int32, tag="1")]
    pub key: i32,
}
// Controller messages 

/// ControllerAttach message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoControllerAttach {
    /// One of the following enums: "ps", "xbox" or "switch"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Session specific slot number (0-3)
    #[prost(int32, tag="2")]
    pub session_slot: i32,
    /// Session ID of the client
    #[prost(string, tag="3")]
    pub session_id: ::prost::alloc::string::String,
}
/// ControllerDetach message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoControllerDetach {
    /// Session specific slot number (0-3)
    #[prost(int32, tag="1")]
    pub session_slot: i32,
    /// Session ID of the client
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
}
/// ControllerRumble message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoControllerRumble {
    /// Session specific slot number (0-3)
    #[prost(int32, tag="1")]
    pub session_slot: i32,
    /// Session ID of the client
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    /// Low frequency rumble (0-65535)
    #[prost(int32, tag="3")]
    pub low_frequency: i32,
    /// High frequency rumble (0-65535)
    #[prost(int32, tag="4")]
    pub high_frequency: i32,
    /// Duration in milliseconds
    #[prost(int32, tag="5")]
    pub duration: i32,
}
/// ControllerStateBatch - single message containing full or partial controller state
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoControllerStateBatch {
    /// Session specific slot number (0-3)
    #[prost(int32, tag="1")]
    pub session_slot: i32,
    /// Session ID of the client
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(enumeration="proto_controller_state_batch::UpdateType", tag="3")]
    pub update_type: i32,
    /// Sequence number for packet loss detection
    #[prost(uint32, tag="4")]
    pub sequence: u32,
    /// Button state map (Linux event codes)
    #[prost(map="int32, bool", tag="5")]
    pub button_changed_mask: ::std::collections::HashMap<i32, bool>,
    /// Analog inputs
    ///
    /// -32768 to 32767
    #[prost(int32, optional, tag="6")]
    pub left_stick_x: ::core::option::Option<i32>,
    /// -32768 to 32767
    #[prost(int32, optional, tag="7")]
    pub left_stick_y: ::core::option::Option<i32>,
    /// -32768 to 32767
    #[prost(int32, optional, tag="8")]
    pub right_stick_x: ::core::option::Option<i32>,
    /// -32768 to 32767
    #[prost(int32, optional, tag="9")]
    pub right_stick_y: ::core::option::Option<i32>,
    /// -32768 to 32767
    #[prost(int32, optional, tag="10")]
    pub left_trigger: ::core::option::Option<i32>,
    /// -32768 to 32767
    #[prost(int32, optional, tag="11")]
    pub right_trigger: ::core::option::Option<i32>,
    /// -1, 0, or 1
    #[prost(int32, optional, tag="12")]
    pub dpad_x: ::core::option::Option<i32>,
    /// -1, 0, or 1
    #[prost(int32, optional, tag="13")]
    pub dpad_y: ::core::option::Option<i32>,
    /// Bitmask indicating which fields have changed
    /// Bit 0: button_changed_mask, Bit 1: left_stick_x, Bit 2: left_stick_y, etc.
    #[prost(uint32, optional, tag="14")]
    pub changed_fields: ::core::option::Option<u32>,
}
/// Nested message and enum types in `ProtoControllerStateBatch`.
pub mod proto_controller_state_batch {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum UpdateType {
        /// Complete controller state
        FullState = 0,
        /// Only changed fields
        Delta = 1,
    }
    impl UpdateType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                UpdateType::FullState => "FULL_STATE",
                UpdateType::Delta => "DELTA",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FULL_STATE" => Some(Self::FullState),
                "DELTA" => Some(Self::Delta),
                _ => None,
            }
        }
    }
}
// WebRTC + signaling 

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtcIceCandidateInit {
    #[prost(string, tag="1")]
    pub candidate: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag="2")]
    pub sdp_m_line_index: ::core::option::Option<u32>,
    #[prost(string, optional, tag="3")]
    pub sdp_mid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub username_fragment: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtcSessionDescriptionInit {
    #[prost(string, tag="1")]
    pub sdp: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub r#type: ::prost::alloc::string::String,
}
/// ProtoICE message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoIce {
    #[prost(message, optional, tag="1")]
    pub candidate: ::core::option::Option<RtcIceCandidateInit>,
}
/// ProtoSDP message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoSdp {
    #[prost(message, optional, tag="1")]
    pub sdp: ::core::option::Option<RtcSessionDescriptionInit>,
}
/// ProtoRaw message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoRaw {
    #[prost(string, tag="1")]
    pub data: ::prost::alloc::string::String,
}
/// ProtoClientRequestRoomStream message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoClientRequestRoomStream {
    #[prost(string, tag="1")]
    pub room_name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
}
/// ProtoClientDisconnected message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoClientDisconnected {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag="2")]
    pub controller_slots: ::prost::alloc::vec::Vec<i32>,
}
/// ProtoServerPushStream message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoServerPushStream {
    #[prost(string, tag="1")]
    pub room_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoMessageBase {
    #[prost(string, tag="1")]
    pub payload_type: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub latency: ::core::option::Option<ProtoLatencyTracker>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoMessage {
    #[prost(message, optional, tag="1")]
    pub message_base: ::core::option::Option<ProtoMessageBase>,
    #[prost(oneof="proto_message::Payload", tags="2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 20, 21, 22, 23, 24, 25")]
    pub payload: ::core::option::Option<proto_message::Payload>,
}
/// Nested message and enum types in `ProtoMessage`.
pub mod proto_message {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// Input types
        #[prost(message, tag="2")]
        MouseMove(super::ProtoMouseMove),
        #[prost(message, tag="3")]
        MouseMoveAbs(super::ProtoMouseMoveAbs),
        #[prost(message, tag="4")]
        MouseWheel(super::ProtoMouseWheel),
        #[prost(message, tag="5")]
        MouseKeyDown(super::ProtoMouseKeyDown),
        #[prost(message, tag="6")]
        MouseKeyUp(super::ProtoMouseKeyUp),
        #[prost(message, tag="7")]
        KeyDown(super::ProtoKeyDown),
        #[prost(message, tag="8")]
        KeyUp(super::ProtoKeyUp),
        /// Controller input types
        #[prost(message, tag="9")]
        ControllerAttach(super::ProtoControllerAttach),
        #[prost(message, tag="10")]
        ControllerDetach(super::ProtoControllerDetach),
        #[prost(message, tag="11")]
        ControllerRumble(super::ProtoControllerRumble),
        #[prost(message, tag="12")]
        ControllerStateBatch(super::ProtoControllerStateBatch),
        /// Signaling types
        #[prost(message, tag="20")]
        Ice(super::ProtoIce),
        #[prost(message, tag="21")]
        Sdp(super::ProtoSdp),
        #[prost(message, tag="22")]
        Raw(super::ProtoRaw),
        #[prost(message, tag="23")]
        ClientRequestRoomStream(super::ProtoClientRequestRoomStream),
        #[prost(message, tag="24")]
        ClientDisconnected(super::ProtoClientDisconnected),
        #[prost(message, tag="25")]
        ServerPushStream(super::ProtoServerPushStream),
    }
}
// @@protoc_insertion_point(module)
