// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file types.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types.proto.
 */
export const file_types: GenFile = /*@__PURE__*/
  fileDesc("Cgt0eXBlcy5wcm90bxIFcHJvdG8iJgoOUHJvdG9Nb3VzZU1vdmUSCQoBeBgBIAEoBRIJCgF5GAIgASgFIikKEVByb3RvTW91c2VNb3ZlQWJzEgkKAXgYASABKAUSCQoBeRgCIAEoBSInCg9Qcm90b01vdXNlV2hlZWwSCQoBeBgBIAEoBRIJCgF5GAIgASgFIiAKEVByb3RvTW91c2VLZXlEb3duEgsKA2tleRgBIAEoBSIeCg9Qcm90b01vdXNlS2V5VXASCwoDa2V5GAEgASgFIhsKDFByb3RvS2V5RG93bhILCgNrZXkYASABKAUiGQoKUHJvdG9LZXlVcBILCgNrZXkYASABKAUiRQoVUHJvdG9Db250cm9sbGVyQXR0YWNoEgoKAmlkGAEgASgJEgwKBHNsb3QYAiABKAUSEgoKc2Vzc2lvbl9pZBgDIAEoCSIlChVQcm90b0NvbnRyb2xsZXJEZXRhY2gSDAoEc2xvdBgBIAEoBSJGChVQcm90b0NvbnRyb2xsZXJCdXR0b24SDAoEc2xvdBgBIAEoBRIOCgZidXR0b24YAiABKAUSDwoHcHJlc3NlZBgDIAEoCCJGChZQcm90b0NvbnRyb2xsZXJUcmlnZ2VyEgwKBHNsb3QYASABKAUSDwoHdHJpZ2dlchgCIAEoBRINCgV2YWx1ZRgDIAEoBSJJChRQcm90b0NvbnRyb2xsZXJTdGljaxIMCgRzbG90GAEgASgFEg0KBXN0aWNrGAIgASgFEgkKAXgYAyABKAUSCQoBeRgEIAEoBSJAChNQcm90b0NvbnRyb2xsZXJBeGlzEgwKBHNsb3QYASABKAUSDAoEYXhpcxgCIAEoBRINCgV2YWx1ZRgDIAEoBSJmChVQcm90b0NvbnRyb2xsZXJSdW1ibGUSDAoEc2xvdBgBIAEoBRIVCg1sb3dfZnJlcXVlbmN5GAIgASgFEhYKDmhpZ2hfZnJlcXVlbmN5GAMgASgFEhAKCGR1cmF0aW9uGAQgASgFIqoBChNSVENJY2VDYW5kaWRhdGVJbml0EhEKCWNhbmRpZGF0ZRgBIAEoCRIaCg1zZHBNTGluZUluZGV4GAIgASgNSACIAQESEwoGc2RwTWlkGAMgASgJSAGIAQESHQoQdXNlcm5hbWVGcmFnbWVudBgEIAEoCUgCiAEBQhAKDl9zZHBNTGluZUluZGV4QgkKB19zZHBNaWRCEwoRX3VzZXJuYW1lRnJhZ21lbnQiNgoZUlRDU2Vzc2lvbkRlc2NyaXB0aW9uSW5pdBILCgNzZHAYASABKAkSDAoEdHlwZRgCIAEoCSI5CghQcm90b0lDRRItCgljYW5kaWRhdGUYASABKAsyGi5wcm90by5SVENJY2VDYW5kaWRhdGVJbml0IjkKCFByb3RvU0RQEi0KA3NkcBgBIAEoCzIgLnByb3RvLlJUQ1Nlc3Npb25EZXNjcmlwdGlvbkluaXQiGAoIUHJvdG9SYXcSDAoEZGF0YRgBIAEoCSJFChxQcm90b0NsaWVudFJlcXVlc3RSb29tU3RyZWFtEhEKCXJvb21fbmFtZRgBIAEoCRISCgpzZXNzaW9uX2lkGAIgASgJIkcKF1Byb3RvQ2xpZW50RGlzY29ubmVjdGVkEhIKCnNlc3Npb25faWQYASABKAkSGAoQY29udHJvbGxlcl9zbG90cxgCIAMoBSIqChVQcm90b1NlcnZlclB1c2hTdHJlYW0SEQoJcm9vbV9uYW1lGAEgASgJQhZaFHJlbGF5L2ludGVybmFsL3Byb3RvYgZwcm90bzM");

/**
 * MouseMove message
 *
 * @generated from message proto.ProtoMouseMove
 */
export type ProtoMouseMove = Message<"proto.ProtoMouseMove"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message proto.ProtoMouseMove.
 * Use `create(ProtoMouseMoveSchema)` to create a new message.
 */
export const ProtoMouseMoveSchema: GenMessage<ProtoMouseMove> = /*@__PURE__*/
  messageDesc(file_types, 0);

/**
 * MouseMoveAbs message
 *
 * @generated from message proto.ProtoMouseMoveAbs
 */
export type ProtoMouseMoveAbs = Message<"proto.ProtoMouseMoveAbs"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message proto.ProtoMouseMoveAbs.
 * Use `create(ProtoMouseMoveAbsSchema)` to create a new message.
 */
export const ProtoMouseMoveAbsSchema: GenMessage<ProtoMouseMoveAbs> = /*@__PURE__*/
  messageDesc(file_types, 1);

/**
 * MouseWheel message
 *
 * @generated from message proto.ProtoMouseWheel
 */
export type ProtoMouseWheel = Message<"proto.ProtoMouseWheel"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message proto.ProtoMouseWheel.
 * Use `create(ProtoMouseWheelSchema)` to create a new message.
 */
export const ProtoMouseWheelSchema: GenMessage<ProtoMouseWheel> = /*@__PURE__*/
  messageDesc(file_types, 2);

/**
 * MouseKeyDown message
 *
 * @generated from message proto.ProtoMouseKeyDown
 */
export type ProtoMouseKeyDown = Message<"proto.ProtoMouseKeyDown"> & {
  /**
   * @generated from field: int32 key = 1;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoMouseKeyDown.
 * Use `create(ProtoMouseKeyDownSchema)` to create a new message.
 */
export const ProtoMouseKeyDownSchema: GenMessage<ProtoMouseKeyDown> = /*@__PURE__*/
  messageDesc(file_types, 3);

/**
 * MouseKeyUp message
 *
 * @generated from message proto.ProtoMouseKeyUp
 */
export type ProtoMouseKeyUp = Message<"proto.ProtoMouseKeyUp"> & {
  /**
   * @generated from field: int32 key = 1;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoMouseKeyUp.
 * Use `create(ProtoMouseKeyUpSchema)` to create a new message.
 */
export const ProtoMouseKeyUpSchema: GenMessage<ProtoMouseKeyUp> = /*@__PURE__*/
  messageDesc(file_types, 4);

/**
 * KeyDown message
 *
 * @generated from message proto.ProtoKeyDown
 */
export type ProtoKeyDown = Message<"proto.ProtoKeyDown"> & {
  /**
   * @generated from field: int32 key = 1;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoKeyDown.
 * Use `create(ProtoKeyDownSchema)` to create a new message.
 */
export const ProtoKeyDownSchema: GenMessage<ProtoKeyDown> = /*@__PURE__*/
  messageDesc(file_types, 5);

/**
 * KeyUp message
 *
 * @generated from message proto.ProtoKeyUp
 */
export type ProtoKeyUp = Message<"proto.ProtoKeyUp"> & {
  /**
   * @generated from field: int32 key = 1;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoKeyUp.
 * Use `create(ProtoKeyUpSchema)` to create a new message.
 */
export const ProtoKeyUpSchema: GenMessage<ProtoKeyUp> = /*@__PURE__*/
  messageDesc(file_types, 6);

/**
 * ControllerAttach message
 *
 * @generated from message proto.ProtoControllerAttach
 */
export type ProtoControllerAttach = Message<"proto.ProtoControllerAttach"> & {
  /**
   * One of the following enums: "ps", "xbox" or "switch"
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Slot number (0-3)
   *
   * @generated from field: int32 slot = 2;
   */
  slot: number;

  /**
   * Session ID of the client attaching the controller
   *
   * @generated from field: string session_id = 3;
   */
  sessionId: string;
};

/**
 * Describes the message proto.ProtoControllerAttach.
 * Use `create(ProtoControllerAttachSchema)` to create a new message.
 */
export const ProtoControllerAttachSchema: GenMessage<ProtoControllerAttach> = /*@__PURE__*/
  messageDesc(file_types, 7);

/**
 * ControllerDetach message
 *
 * @generated from message proto.ProtoControllerDetach
 */
export type ProtoControllerDetach = Message<"proto.ProtoControllerDetach"> & {
  /**
   * Slot number (0-3)
   *
   * @generated from field: int32 slot = 1;
   */
  slot: number;
};

/**
 * Describes the message proto.ProtoControllerDetach.
 * Use `create(ProtoControllerDetachSchema)` to create a new message.
 */
export const ProtoControllerDetachSchema: GenMessage<ProtoControllerDetach> = /*@__PURE__*/
  messageDesc(file_types, 8);

/**
 * ControllerButton message
 *
 * @generated from message proto.ProtoControllerButton
 */
export type ProtoControllerButton = Message<"proto.ProtoControllerButton"> & {
  /**
   * Slot number (0-3)
   *
   * @generated from field: int32 slot = 1;
   */
  slot: number;

  /**
   * Button code (linux input event code)
   *
   * @generated from field: int32 button = 2;
   */
  button: number;

  /**
   * true if pressed, false if released
   *
   * @generated from field: bool pressed = 3;
   */
  pressed: boolean;
};

/**
 * Describes the message proto.ProtoControllerButton.
 * Use `create(ProtoControllerButtonSchema)` to create a new message.
 */
export const ProtoControllerButtonSchema: GenMessage<ProtoControllerButton> = /*@__PURE__*/
  messageDesc(file_types, 9);

/**
 * ControllerTriggers message
 *
 * @generated from message proto.ProtoControllerTrigger
 */
export type ProtoControllerTrigger = Message<"proto.ProtoControllerTrigger"> & {
  /**
   * Slot number (0-3)
   *
   * @generated from field: int32 slot = 1;
   */
  slot: number;

  /**
   * Trigger number (0 for left, 1 for right)
   *
   * @generated from field: int32 trigger = 2;
   */
  trigger: number;

  /**
   * trigger value (-32768 to 32767)
   *
   * @generated from field: int32 value = 3;
   */
  value: number;
};

/**
 * Describes the message proto.ProtoControllerTrigger.
 * Use `create(ProtoControllerTriggerSchema)` to create a new message.
 */
export const ProtoControllerTriggerSchema: GenMessage<ProtoControllerTrigger> = /*@__PURE__*/
  messageDesc(file_types, 10);

/**
 * ControllerSticks message
 *
 * @generated from message proto.ProtoControllerStick
 */
export type ProtoControllerStick = Message<"proto.ProtoControllerStick"> & {
  /**
   * Slot number (0-3)
   *
   * @generated from field: int32 slot = 1;
   */
  slot: number;

  /**
   * Stick number (0 for left, 1 for right)
   *
   * @generated from field: int32 stick = 2;
   */
  stick: number;

  /**
   * X axis value (-32768 to 32767)
   *
   * @generated from field: int32 x = 3;
   */
  x: number;

  /**
   * Y axis value (-32768 to 32767)
   *
   * @generated from field: int32 y = 4;
   */
  y: number;
};

/**
 * Describes the message proto.ProtoControllerStick.
 * Use `create(ProtoControllerStickSchema)` to create a new message.
 */
export const ProtoControllerStickSchema: GenMessage<ProtoControllerStick> = /*@__PURE__*/
  messageDesc(file_types, 11);

/**
 * ControllerAxis message
 *
 * @generated from message proto.ProtoControllerAxis
 */
export type ProtoControllerAxis = Message<"proto.ProtoControllerAxis"> & {
  /**
   * Slot number (0-3)
   *
   * @generated from field: int32 slot = 1;
   */
  slot: number;

  /**
   * Axis number (0 for d-pad horizontal, 1 for d-pad vertical)
   *
   * @generated from field: int32 axis = 2;
   */
  axis: number;

  /**
   * axis value (-1 to 1)
   *
   * @generated from field: int32 value = 3;
   */
  value: number;
};

/**
 * Describes the message proto.ProtoControllerAxis.
 * Use `create(ProtoControllerAxisSchema)` to create a new message.
 */
export const ProtoControllerAxisSchema: GenMessage<ProtoControllerAxis> = /*@__PURE__*/
  messageDesc(file_types, 12);

/**
 * ControllerRumble message
 *
 * @generated from message proto.ProtoControllerRumble
 */
export type ProtoControllerRumble = Message<"proto.ProtoControllerRumble"> & {
  /**
   * Slot number (0-3)
   *
   * @generated from field: int32 slot = 1;
   */
  slot: number;

  /**
   * Low frequency rumble (0-65535)
   *
   * @generated from field: int32 low_frequency = 2;
   */
  lowFrequency: number;

  /**
   * High frequency rumble (0-65535)
   *
   * @generated from field: int32 high_frequency = 3;
   */
  highFrequency: number;

  /**
   * Duration in milliseconds
   *
   * @generated from field: int32 duration = 4;
   */
  duration: number;
};

/**
 * Describes the message proto.ProtoControllerRumble.
 * Use `create(ProtoControllerRumbleSchema)` to create a new message.
 */
export const ProtoControllerRumbleSchema: GenMessage<ProtoControllerRumble> = /*@__PURE__*/
  messageDesc(file_types, 13);

/**
 * @generated from message proto.RTCIceCandidateInit
 */
export type RTCIceCandidateInit = Message<"proto.RTCIceCandidateInit"> & {
  /**
   * @generated from field: string candidate = 1;
   */
  candidate: string;

  /**
   * @generated from field: optional uint32 sdpMLineIndex = 2;
   */
  sdpMLineIndex?: number;

  /**
   * @generated from field: optional string sdpMid = 3;
   */
  sdpMid?: string;

  /**
   * @generated from field: optional string usernameFragment = 4;
   */
  usernameFragment?: string;
};

/**
 * Describes the message proto.RTCIceCandidateInit.
 * Use `create(RTCIceCandidateInitSchema)` to create a new message.
 */
export const RTCIceCandidateInitSchema: GenMessage<RTCIceCandidateInit> = /*@__PURE__*/
  messageDesc(file_types, 14);

/**
 * @generated from message proto.RTCSessionDescriptionInit
 */
export type RTCSessionDescriptionInit = Message<"proto.RTCSessionDescriptionInit"> & {
  /**
   * @generated from field: string sdp = 1;
   */
  sdp: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;
};

/**
 * Describes the message proto.RTCSessionDescriptionInit.
 * Use `create(RTCSessionDescriptionInitSchema)` to create a new message.
 */
export const RTCSessionDescriptionInitSchema: GenMessage<RTCSessionDescriptionInit> = /*@__PURE__*/
  messageDesc(file_types, 15);

/**
 * ProtoICE message
 *
 * @generated from message proto.ProtoICE
 */
export type ProtoICE = Message<"proto.ProtoICE"> & {
  /**
   * @generated from field: proto.RTCIceCandidateInit candidate = 1;
   */
  candidate?: RTCIceCandidateInit;
};

/**
 * Describes the message proto.ProtoICE.
 * Use `create(ProtoICESchema)` to create a new message.
 */
export const ProtoICESchema: GenMessage<ProtoICE> = /*@__PURE__*/
  messageDesc(file_types, 16);

/**
 * ProtoSDP message
 *
 * @generated from message proto.ProtoSDP
 */
export type ProtoSDP = Message<"proto.ProtoSDP"> & {
  /**
   * @generated from field: proto.RTCSessionDescriptionInit sdp = 1;
   */
  sdp?: RTCSessionDescriptionInit;
};

/**
 * Describes the message proto.ProtoSDP.
 * Use `create(ProtoSDPSchema)` to create a new message.
 */
export const ProtoSDPSchema: GenMessage<ProtoSDP> = /*@__PURE__*/
  messageDesc(file_types, 17);

/**
 * ProtoRaw message
 *
 * @generated from message proto.ProtoRaw
 */
export type ProtoRaw = Message<"proto.ProtoRaw"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message proto.ProtoRaw.
 * Use `create(ProtoRawSchema)` to create a new message.
 */
export const ProtoRawSchema: GenMessage<ProtoRaw> = /*@__PURE__*/
  messageDesc(file_types, 18);

/**
 * ProtoClientRequestRoomStream message
 *
 * @generated from message proto.ProtoClientRequestRoomStream
 */
export type ProtoClientRequestRoomStream = Message<"proto.ProtoClientRequestRoomStream"> & {
  /**
   * @generated from field: string room_name = 1;
   */
  roomName: string;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;
};

/**
 * Describes the message proto.ProtoClientRequestRoomStream.
 * Use `create(ProtoClientRequestRoomStreamSchema)` to create a new message.
 */
export const ProtoClientRequestRoomStreamSchema: GenMessage<ProtoClientRequestRoomStream> = /*@__PURE__*/
  messageDesc(file_types, 19);

/**
 * ProtoClientDisconnected message
 *
 * @generated from message proto.ProtoClientDisconnected
 */
export type ProtoClientDisconnected = Message<"proto.ProtoClientDisconnected"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: repeated int32 controller_slots = 2;
   */
  controllerSlots: number[];
};

/**
 * Describes the message proto.ProtoClientDisconnected.
 * Use `create(ProtoClientDisconnectedSchema)` to create a new message.
 */
export const ProtoClientDisconnectedSchema: GenMessage<ProtoClientDisconnected> = /*@__PURE__*/
  messageDesc(file_types, 20);

/**
 * ProtoServerPushStream message
 *
 * @generated from message proto.ProtoServerPushStream
 */
export type ProtoServerPushStream = Message<"proto.ProtoServerPushStream"> & {
  /**
   * @generated from field: string room_name = 1;
   */
  roomName: string;
};

/**
 * Describes the message proto.ProtoServerPushStream.
 * Use `create(ProtoServerPushStreamSchema)` to create a new message.
 */
export const ProtoServerPushStreamSchema: GenMessage<ProtoServerPushStream> = /*@__PURE__*/
  messageDesc(file_types, 21);

