// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file types.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types.proto.
 */
export const file_types: GenFile = /*@__PURE__*/
  fileDesc("Cgt0eXBlcy5wcm90bxIFcHJvdG8iIwoOUHJvdG9CYXNlSW5wdXQSEQoJdGltZXN0YW1wGAEgASgDIl8KDlByb3RvTW91c2VNb3ZlEikKCmJhc2VfaW5wdXQYASABKAsyFS5wcm90by5Qcm90b0Jhc2VJbnB1dBIMCgR0eXBlGAIgASgJEgkKAXgYAyABKAUSCQoBeRgEIAEoBSJiChFQcm90b01vdXNlTW92ZUFicxIpCgpiYXNlX2lucHV0GAEgASgLMhUucHJvdG8uUHJvdG9CYXNlSW5wdXQSDAoEdHlwZRgCIAEoCRIJCgF4GAMgASgFEgkKAXkYBCABKAUiYAoPUHJvdG9Nb3VzZVdoZWVsEikKCmJhc2VfaW5wdXQYASABKAsyFS5wcm90by5Qcm90b0Jhc2VJbnB1dBIMCgR0eXBlGAIgASgJEgkKAXgYAyABKAUSCQoBeRgEIAEoBSJZChFQcm90b01vdXNlS2V5RG93bhIpCgpiYXNlX2lucHV0GAEgASgLMhUucHJvdG8uUHJvdG9CYXNlSW5wdXQSDAoEdHlwZRgCIAEoCRILCgNrZXkYAyABKAUiVwoPUHJvdG9Nb3VzZUtleVVwEikKCmJhc2VfaW5wdXQYASABKAsyFS5wcm90by5Qcm90b0Jhc2VJbnB1dBIMCgR0eXBlGAIgASgJEgsKA2tleRgDIAEoBSJUCgxQcm90b0tleURvd24SKQoKYmFzZV9pbnB1dBgBIAEoCzIVLnByb3RvLlByb3RvQmFzZUlucHV0EgwKBHR5cGUYAiABKAkSCwoDa2V5GAMgASgFIlIKClByb3RvS2V5VXASKQoKYmFzZV9pbnB1dBgBIAEoCzIVLnByb3RvLlByb3RvQmFzZUlucHV0EgwKBHR5cGUYAiABKAkSCwoDa2V5GAMgASgFItwCCgpQcm90b0lucHV0EisKCm1vdXNlX21vdmUYASABKAsyFS5wcm90by5Qcm90b01vdXNlTW92ZUgAEjIKDm1vdXNlX21vdmVfYWJzGAIgASgLMhgucHJvdG8uUHJvdG9Nb3VzZU1vdmVBYnNIABItCgttb3VzZV93aGVlbBgDIAEoCzIWLnByb3RvLlByb3RvTW91c2VXaGVlbEgAEjIKDm1vdXNlX2tleV9kb3duGAQgASgLMhgucHJvdG8uUHJvdG9Nb3VzZUtleURvd25IABIuCgxtb3VzZV9rZXlfdXAYBSABKAsyFi5wcm90by5Qcm90b01vdXNlS2V5VXBIABInCghrZXlfZG93bhgGIAEoCzITLnByb3RvLlByb3RvS2V5RG93bkgAEiMKBmtleV91cBgHIAEoCzIRLnByb3RvLlByb3RvS2V5VXBIAEIMCgppbnB1dF90eXBlYgZwcm90bzM");

/**
 * Base message for all input types
 *
 * @generated from message proto.ProtoBaseInput
 */
export type ProtoBaseInput = Message<"proto.ProtoBaseInput"> & {
  /**
   * Optional timestamp
   *
   * @generated from field: int64 timestamp = 1;
   */
  timestamp: bigint;
};

/**
 * Describes the message proto.ProtoBaseInput.
 * Use `create(ProtoBaseInputSchema)` to create a new message.
 */
export const ProtoBaseInputSchema: GenMessage<ProtoBaseInput> = /*@__PURE__*/
  messageDesc(file_types, 0);

/**
 * MouseMove message
 *
 * @generated from message proto.ProtoMouseMove
 */
export type ProtoMouseMove = Message<"proto.ProtoMouseMove"> & {
  /**
   * @generated from field: proto.ProtoBaseInput base_input = 1;
   */
  baseInput?: ProtoBaseInput;

  /**
   * Fixed value "MouseMove"
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: int32 x = 3;
   */
  x: number;

  /**
   * @generated from field: int32 y = 4;
   */
  y: number;
};

/**
 * Describes the message proto.ProtoMouseMove.
 * Use `create(ProtoMouseMoveSchema)` to create a new message.
 */
export const ProtoMouseMoveSchema: GenMessage<ProtoMouseMove> = /*@__PURE__*/
  messageDesc(file_types, 1);

/**
 * MouseMoveAbs message
 *
 * @generated from message proto.ProtoMouseMoveAbs
 */
export type ProtoMouseMoveAbs = Message<"proto.ProtoMouseMoveAbs"> & {
  /**
   * @generated from field: proto.ProtoBaseInput base_input = 1;
   */
  baseInput?: ProtoBaseInput;

  /**
   * Fixed value "MouseMoveAbs"
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: int32 x = 3;
   */
  x: number;

  /**
   * @generated from field: int32 y = 4;
   */
  y: number;
};

/**
 * Describes the message proto.ProtoMouseMoveAbs.
 * Use `create(ProtoMouseMoveAbsSchema)` to create a new message.
 */
export const ProtoMouseMoveAbsSchema: GenMessage<ProtoMouseMoveAbs> = /*@__PURE__*/
  messageDesc(file_types, 2);

/**
 * MouseWheel message
 *
 * @generated from message proto.ProtoMouseWheel
 */
export type ProtoMouseWheel = Message<"proto.ProtoMouseWheel"> & {
  /**
   * @generated from field: proto.ProtoBaseInput base_input = 1;
   */
  baseInput?: ProtoBaseInput;

  /**
   * Fixed value "MouseWheel"
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: int32 x = 3;
   */
  x: number;

  /**
   * @generated from field: int32 y = 4;
   */
  y: number;
};

/**
 * Describes the message proto.ProtoMouseWheel.
 * Use `create(ProtoMouseWheelSchema)` to create a new message.
 */
export const ProtoMouseWheelSchema: GenMessage<ProtoMouseWheel> = /*@__PURE__*/
  messageDesc(file_types, 3);

/**
 * MouseKeyDown message
 *
 * @generated from message proto.ProtoMouseKeyDown
 */
export type ProtoMouseKeyDown = Message<"proto.ProtoMouseKeyDown"> & {
  /**
   * @generated from field: proto.ProtoBaseInput base_input = 1;
   */
  baseInput?: ProtoBaseInput;

  /**
   * Fixed value "MouseKeyDown"
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: int32 key = 3;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoMouseKeyDown.
 * Use `create(ProtoMouseKeyDownSchema)` to create a new message.
 */
export const ProtoMouseKeyDownSchema: GenMessage<ProtoMouseKeyDown> = /*@__PURE__*/
  messageDesc(file_types, 4);

/**
 * MouseKeyUp message
 *
 * @generated from message proto.ProtoMouseKeyUp
 */
export type ProtoMouseKeyUp = Message<"proto.ProtoMouseKeyUp"> & {
  /**
   * @generated from field: proto.ProtoBaseInput base_input = 1;
   */
  baseInput?: ProtoBaseInput;

  /**
   * Fixed value "MouseKeyUp"
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: int32 key = 3;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoMouseKeyUp.
 * Use `create(ProtoMouseKeyUpSchema)` to create a new message.
 */
export const ProtoMouseKeyUpSchema: GenMessage<ProtoMouseKeyUp> = /*@__PURE__*/
  messageDesc(file_types, 5);

/**
 * KeyDown message
 *
 * @generated from message proto.ProtoKeyDown
 */
export type ProtoKeyDown = Message<"proto.ProtoKeyDown"> & {
  /**
   * @generated from field: proto.ProtoBaseInput base_input = 1;
   */
  baseInput?: ProtoBaseInput;

  /**
   * Fixed value "KeyDown"
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: int32 key = 3;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoKeyDown.
 * Use `create(ProtoKeyDownSchema)` to create a new message.
 */
export const ProtoKeyDownSchema: GenMessage<ProtoKeyDown> = /*@__PURE__*/
  messageDesc(file_types, 6);

/**
 * KeyUp message
 *
 * @generated from message proto.ProtoKeyUp
 */
export type ProtoKeyUp = Message<"proto.ProtoKeyUp"> & {
  /**
   * @generated from field: proto.ProtoBaseInput base_input = 1;
   */
  baseInput?: ProtoBaseInput;

  /**
   * Fixed value "KeyUp"
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: int32 key = 3;
   */
  key: number;
};

/**
 * Describes the message proto.ProtoKeyUp.
 * Use `create(ProtoKeyUpSchema)` to create a new message.
 */
export const ProtoKeyUpSchema: GenMessage<ProtoKeyUp> = /*@__PURE__*/
  messageDesc(file_types, 7);

/**
 * Union of all Input types
 *
 * @generated from message proto.ProtoInput
 */
export type ProtoInput = Message<"proto.ProtoInput"> & {
  /**
   * @generated from oneof proto.ProtoInput.input_type
   */
  inputType: {
    /**
     * @generated from field: proto.ProtoMouseMove mouse_move = 1;
     */
    value: ProtoMouseMove;
    case: "mouseMove";
  } | {
    /**
     * @generated from field: proto.ProtoMouseMoveAbs mouse_move_abs = 2;
     */
    value: ProtoMouseMoveAbs;
    case: "mouseMoveAbs";
  } | {
    /**
     * @generated from field: proto.ProtoMouseWheel mouse_wheel = 3;
     */
    value: ProtoMouseWheel;
    case: "mouseWheel";
  } | {
    /**
     * @generated from field: proto.ProtoMouseKeyDown mouse_key_down = 4;
     */
    value: ProtoMouseKeyDown;
    case: "mouseKeyDown";
  } | {
    /**
     * @generated from field: proto.ProtoMouseKeyUp mouse_key_up = 5;
     */
    value: ProtoMouseKeyUp;
    case: "mouseKeyUp";
  } | {
    /**
     * @generated from field: proto.ProtoKeyDown key_down = 6;
     */
    value: ProtoKeyDown;
    case: "keyDown";
  } | {
    /**
     * @generated from field: proto.ProtoKeyUp key_up = 7;
     */
    value: ProtoKeyUp;
    case: "keyUp";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.ProtoInput.
 * Use `create(ProtoInputSchema)` to create a new message.
 */
export const ProtoInputSchema: GenMessage<ProtoInput> = /*@__PURE__*/
  messageDesc(file_types, 8);

