// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoControllerStateBatch_UpdateType int32

const (
	ProtoControllerStateBatch_FULL_STATE ProtoControllerStateBatch_UpdateType = 0 // Complete controller state
	ProtoControllerStateBatch_DELTA      ProtoControllerStateBatch_UpdateType = 1 // Only changed fields
)

// Enum value maps for ProtoControllerStateBatch_UpdateType.
var (
	ProtoControllerStateBatch_UpdateType_name = map[int32]string{
		0: "FULL_STATE",
		1: "DELTA",
	}
	ProtoControllerStateBatch_UpdateType_value = map[string]int32{
		"FULL_STATE": 0,
		"DELTA":      1,
	}
)

func (x ProtoControllerStateBatch_UpdateType) Enum() *ProtoControllerStateBatch_UpdateType {
	p := new(ProtoControllerStateBatch_UpdateType)
	*p = x
	return p
}

func (x ProtoControllerStateBatch_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoControllerStateBatch_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ProtoControllerStateBatch_UpdateType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ProtoControllerStateBatch_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoControllerStateBatch_UpdateType.Descriptor instead.
func (ProtoControllerStateBatch_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10, 0}
}

// MouseMove message
type ProtoMouseMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseMove) Reset() {
	*x = ProtoMouseMove{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseMove) ProtoMessage() {}

func (x *ProtoMouseMove) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseMove.ProtoReflect.Descriptor instead.
func (*ProtoMouseMove) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMouseMove) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseMove) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseMoveAbs message
type ProtoMouseMoveAbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseMoveAbs) Reset() {
	*x = ProtoMouseMoveAbs{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseMoveAbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseMoveAbs) ProtoMessage() {}

func (x *ProtoMouseMoveAbs) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseMoveAbs.ProtoReflect.Descriptor instead.
func (*ProtoMouseMoveAbs) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoMouseMoveAbs) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseMoveAbs) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseWheel message
type ProtoMouseWheel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseWheel) Reset() {
	*x = ProtoMouseWheel{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseWheel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseWheel) ProtoMessage() {}

func (x *ProtoMouseWheel) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseWheel.ProtoReflect.Descriptor instead.
func (*ProtoMouseWheel) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoMouseWheel) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseWheel) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseKeyDown message
type ProtoMouseKeyDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseKeyDown) Reset() {
	*x = ProtoMouseKeyDown{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseKeyDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseKeyDown) ProtoMessage() {}

func (x *ProtoMouseKeyDown) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseKeyDown.ProtoReflect.Descriptor instead.
func (*ProtoMouseKeyDown) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoMouseKeyDown) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// MouseKeyUp message
type ProtoMouseKeyUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseKeyUp) Reset() {
	*x = ProtoMouseKeyUp{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseKeyUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseKeyUp) ProtoMessage() {}

func (x *ProtoMouseKeyUp) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseKeyUp.ProtoReflect.Descriptor instead.
func (*ProtoMouseKeyUp) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoMouseKeyUp) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// KeyDown message
type ProtoKeyDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoKeyDown) Reset() {
	*x = ProtoKeyDown{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoKeyDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoKeyDown) ProtoMessage() {}

func (x *ProtoKeyDown) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoKeyDown.ProtoReflect.Descriptor instead.
func (*ProtoKeyDown) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoKeyDown) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// KeyUp message
type ProtoKeyUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoKeyUp) Reset() {
	*x = ProtoKeyUp{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoKeyUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoKeyUp) ProtoMessage() {}

func (x *ProtoKeyUp) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoKeyUp.ProtoReflect.Descriptor instead.
func (*ProtoKeyUp) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoKeyUp) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// ControllerAttach message
type ProtoControllerAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                       // One of the following enums: "ps", "xbox" or "switch"
	SessionSlot   int32                  `protobuf:"varint,2,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerAttach) Reset() {
	*x = ProtoControllerAttach{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerAttach) ProtoMessage() {}

func (x *ProtoControllerAttach) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerAttach.ProtoReflect.Descriptor instead.
func (*ProtoControllerAttach) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoControllerAttach) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtoControllerAttach) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerAttach) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ControllerDetach message
type ProtoControllerDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerDetach) Reset() {
	*x = ProtoControllerDetach{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerDetach) ProtoMessage() {}

func (x *ProtoControllerDetach) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerDetach.ProtoReflect.Descriptor instead.
func (*ProtoControllerDetach) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *ProtoControllerDetach) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerDetach) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ControllerRumble message
type ProtoControllerRumble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"`       // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // Session ID of the client
	LowFrequency  int32                  `protobuf:"varint,3,opt,name=low_frequency,json=lowFrequency,proto3" json:"low_frequency,omitempty"`    // Low frequency rumble (0-65535)
	HighFrequency int32                  `protobuf:"varint,4,opt,name=high_frequency,json=highFrequency,proto3" json:"high_frequency,omitempty"` // High frequency rumble (0-65535)
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                                // Duration in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerRumble) Reset() {
	*x = ProtoControllerRumble{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerRumble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerRumble) ProtoMessage() {}

func (x *ProtoControllerRumble) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerRumble.ProtoReflect.Descriptor instead.
func (*ProtoControllerRumble) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *ProtoControllerRumble) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerRumble) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoControllerRumble) GetLowFrequency() int32 {
	if x != nil {
		return x.LowFrequency
	}
	return 0
}

func (x *ProtoControllerRumble) GetHighFrequency() int32 {
	if x != nil {
		return x.HighFrequency
	}
	return 0
}

func (x *ProtoControllerRumble) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// ControllerStateBatch - single message containing full or partial controller state
type ProtoControllerStateBatch struct {
	state       protoimpl.MessageState               `protogen:"open.v1"`
	SessionSlot int32                                `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId   string                               `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	UpdateType  ProtoControllerStateBatch_UpdateType `protobuf:"varint,3,opt,name=update_type,json=updateType,proto3,enum=proto.ProtoControllerStateBatch_UpdateType" json:"update_type,omitempty"`
	// Sequence number for packet loss detection
	Sequence uint32 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Button state map (Linux event codes)
	ButtonChangedMask map[int32]bool `protobuf:"bytes,5,rep,name=button_changed_mask,json=buttonChangedMask,proto3" json:"button_changed_mask,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Analog inputs
	LeftStickX   *int32 `protobuf:"varint,6,opt,name=left_stick_x,json=leftStickX,proto3,oneof" json:"left_stick_x,omitempty"`      // -32768 to 32767
	LeftStickY   *int32 `protobuf:"varint,7,opt,name=left_stick_y,json=leftStickY,proto3,oneof" json:"left_stick_y,omitempty"`      // -32768 to 32767
	RightStickX  *int32 `protobuf:"varint,8,opt,name=right_stick_x,json=rightStickX,proto3,oneof" json:"right_stick_x,omitempty"`   // -32768 to 32767
	RightStickY  *int32 `protobuf:"varint,9,opt,name=right_stick_y,json=rightStickY,proto3,oneof" json:"right_stick_y,omitempty"`   // -32768 to 32767
	LeftTrigger  *int32 `protobuf:"varint,10,opt,name=left_trigger,json=leftTrigger,proto3,oneof" json:"left_trigger,omitempty"`    // -32768 to 32767
	RightTrigger *int32 `protobuf:"varint,11,opt,name=right_trigger,json=rightTrigger,proto3,oneof" json:"right_trigger,omitempty"` // -32768 to 32767
	DpadX        *int32 `protobuf:"varint,12,opt,name=dpad_x,json=dpadX,proto3,oneof" json:"dpad_x,omitempty"`                      // -1, 0, or 1
	DpadY        *int32 `protobuf:"varint,13,opt,name=dpad_y,json=dpadY,proto3,oneof" json:"dpad_y,omitempty"`                      // -1, 0, or 1
	// Bitmask indicating which fields have changed
	// Bit 0: button_changed_mask, Bit 1: left_stick_x, Bit 2: left_stick_y, etc.
	ChangedFields *uint32 `protobuf:"varint,14,opt,name=changed_fields,json=changedFields,proto3,oneof" json:"changed_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerStateBatch) Reset() {
	*x = ProtoControllerStateBatch{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerStateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerStateBatch) ProtoMessage() {}

func (x *ProtoControllerStateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerStateBatch.ProtoReflect.Descriptor instead.
func (*ProtoControllerStateBatch) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *ProtoControllerStateBatch) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoControllerStateBatch) GetUpdateType() ProtoControllerStateBatch_UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return ProtoControllerStateBatch_FULL_STATE
}

func (x *ProtoControllerStateBatch) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetButtonChangedMask() map[int32]bool {
	if x != nil {
		return x.ButtonChangedMask
	}
	return nil
}

func (x *ProtoControllerStateBatch) GetLeftStickX() int32 {
	if x != nil && x.LeftStickX != nil {
		return *x.LeftStickX
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetLeftStickY() int32 {
	if x != nil && x.LeftStickY != nil {
		return *x.LeftStickY
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetRightStickX() int32 {
	if x != nil && x.RightStickX != nil {
		return *x.RightStickX
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetRightStickY() int32 {
	if x != nil && x.RightStickY != nil {
		return *x.RightStickY
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetLeftTrigger() int32 {
	if x != nil && x.LeftTrigger != nil {
		return *x.LeftTrigger
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetRightTrigger() int32 {
	if x != nil && x.RightTrigger != nil {
		return *x.RightTrigger
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetDpadX() int32 {
	if x != nil && x.DpadX != nil {
		return *x.DpadX
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetDpadY() int32 {
	if x != nil && x.DpadY != nil {
		return *x.DpadY
	}
	return 0
}

func (x *ProtoControllerStateBatch) GetChangedFields() uint32 {
	if x != nil && x.ChangedFields != nil {
		return *x.ChangedFields
	}
	return 0
}

type RTCIceCandidateInit struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMLineIndex    *uint32                `protobuf:"varint,2,opt,name=sdpMLineIndex,proto3,oneof" json:"sdpMLineIndex,omitempty"`
	SdpMid           *string                `protobuf:"bytes,3,opt,name=sdpMid,proto3,oneof" json:"sdpMid,omitempty"`
	UsernameFragment *string                `protobuf:"bytes,4,opt,name=usernameFragment,proto3,oneof" json:"usernameFragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RTCIceCandidateInit) Reset() {
	*x = RTCIceCandidateInit{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTCIceCandidateInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTCIceCandidateInit) ProtoMessage() {}

func (x *RTCIceCandidateInit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTCIceCandidateInit.ProtoReflect.Descriptor instead.
func (*RTCIceCandidateInit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

func (x *RTCIceCandidateInit) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *RTCIceCandidateInit) GetSdpMLineIndex() uint32 {
	if x != nil && x.SdpMLineIndex != nil {
		return *x.SdpMLineIndex
	}
	return 0
}

func (x *RTCIceCandidateInit) GetSdpMid() string {
	if x != nil && x.SdpMid != nil {
		return *x.SdpMid
	}
	return ""
}

func (x *RTCIceCandidateInit) GetUsernameFragment() string {
	if x != nil && x.UsernameFragment != nil {
		return *x.UsernameFragment
	}
	return ""
}

type RTCSessionDescriptionInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTCSessionDescriptionInit) Reset() {
	*x = RTCSessionDescriptionInit{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTCSessionDescriptionInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTCSessionDescriptionInit) ProtoMessage() {}

func (x *RTCSessionDescriptionInit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTCSessionDescriptionInit.ProtoReflect.Descriptor instead.
func (*RTCSessionDescriptionInit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

func (x *RTCSessionDescriptionInit) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *RTCSessionDescriptionInit) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ProtoICE message
type ProtoICE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     *RTCIceCandidateInit   `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoICE) Reset() {
	*x = ProtoICE{}
	mi := &file_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoICE) ProtoMessage() {}

func (x *ProtoICE) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoICE.ProtoReflect.Descriptor instead.
func (*ProtoICE) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{13}
}

func (x *ProtoICE) GetCandidate() *RTCIceCandidateInit {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// ProtoSDP message
type ProtoSDP struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sdp           *RTCSessionDescriptionInit `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSDP) Reset() {
	*x = ProtoSDP{}
	mi := &file_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSDP) ProtoMessage() {}

func (x *ProtoSDP) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSDP.ProtoReflect.Descriptor instead.
func (*ProtoSDP) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{14}
}

func (x *ProtoSDP) GetSdp() *RTCSessionDescriptionInit {
	if x != nil {
		return x.Sdp
	}
	return nil
}

// ProtoRaw message
type ProtoRaw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoRaw) Reset() {
	*x = ProtoRaw{}
	mi := &file_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoRaw) ProtoMessage() {}

func (x *ProtoRaw) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoRaw.ProtoReflect.Descriptor instead.
func (*ProtoRaw) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{15}
}

func (x *ProtoRaw) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// ProtoClientRequestRoomStream message
type ProtoClientRequestRoomStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoClientRequestRoomStream) Reset() {
	*x = ProtoClientRequestRoomStream{}
	mi := &file_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoClientRequestRoomStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoClientRequestRoomStream) ProtoMessage() {}

func (x *ProtoClientRequestRoomStream) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoClientRequestRoomStream.ProtoReflect.Descriptor instead.
func (*ProtoClientRequestRoomStream) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{16}
}

func (x *ProtoClientRequestRoomStream) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ProtoClientRequestRoomStream) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ProtoClientDisconnected message
type ProtoClientDisconnected struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ControllerSlots []int32                `protobuf:"varint,2,rep,packed,name=controller_slots,json=controllerSlots,proto3" json:"controller_slots,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProtoClientDisconnected) Reset() {
	*x = ProtoClientDisconnected{}
	mi := &file_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoClientDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoClientDisconnected) ProtoMessage() {}

func (x *ProtoClientDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoClientDisconnected.ProtoReflect.Descriptor instead.
func (*ProtoClientDisconnected) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{17}
}

func (x *ProtoClientDisconnected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoClientDisconnected) GetControllerSlots() []int32 {
	if x != nil {
		return x.ControllerSlots
	}
	return nil
}

// ProtoServerPushStream message
type ProtoServerPushStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoServerPushStream) Reset() {
	*x = ProtoServerPushStream{}
	mi := &file_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoServerPushStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoServerPushStream) ProtoMessage() {}

func (x *ProtoServerPushStream) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoServerPushStream.ProtoReflect.Descriptor instead.
func (*ProtoServerPushStream) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{18}
}

func (x *ProtoServerPushStream) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05proto\",\n" +
	"\x0eProtoMouseMove\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"/\n" +
	"\x11ProtoMouseMoveAbs\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"-\n" +
	"\x0fProtoMouseWheel\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"%\n" +
	"\x11ProtoMouseKeyDown\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\"#\n" +
	"\x0fProtoMouseKeyUp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\" \n" +
	"\fProtoKeyDown\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\"\x1e\n" +
	"\n" +
	"ProtoKeyUp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\"i\n" +
	"\x15ProtoControllerAttach\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fsession_slot\x18\x02 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"Y\n" +
	"\x15ProtoControllerDetach\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xc1\x01\n" +
	"\x15ProtoControllerRumble\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rlow_frequency\x18\x03 \x01(\x05R\flowFrequency\x12%\n" +
	"\x0ehigh_frequency\x18\x04 \x01(\x05R\rhighFrequency\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\"\x87\a\n" +
	"\x19ProtoControllerStateBatch\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12L\n" +
	"\vupdate_type\x18\x03 \x01(\x0e2+.proto.ProtoControllerStateBatch.UpdateTypeR\n" +
	"updateType\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\rR\bsequence\x12g\n" +
	"\x13button_changed_mask\x18\x05 \x03(\v27.proto.ProtoControllerStateBatch.ButtonChangedMaskEntryR\x11buttonChangedMask\x12%\n" +
	"\fleft_stick_x\x18\x06 \x01(\x05H\x00R\n" +
	"leftStickX\x88\x01\x01\x12%\n" +
	"\fleft_stick_y\x18\a \x01(\x05H\x01R\n" +
	"leftStickY\x88\x01\x01\x12'\n" +
	"\rright_stick_x\x18\b \x01(\x05H\x02R\vrightStickX\x88\x01\x01\x12'\n" +
	"\rright_stick_y\x18\t \x01(\x05H\x03R\vrightStickY\x88\x01\x01\x12&\n" +
	"\fleft_trigger\x18\n" +
	" \x01(\x05H\x04R\vleftTrigger\x88\x01\x01\x12(\n" +
	"\rright_trigger\x18\v \x01(\x05H\x05R\frightTrigger\x88\x01\x01\x12\x1a\n" +
	"\x06dpad_x\x18\f \x01(\x05H\x06R\x05dpadX\x88\x01\x01\x12\x1a\n" +
	"\x06dpad_y\x18\r \x01(\x05H\aR\x05dpadY\x88\x01\x01\x12*\n" +
	"\x0echanged_fields\x18\x0e \x01(\rH\bR\rchangedFields\x88\x01\x01\x1aD\n" +
	"\x16ButtonChangedMaskEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"'\n" +
	"\n" +
	"UpdateType\x12\x0e\n" +
	"\n" +
	"FULL_STATE\x10\x00\x12\t\n" +
	"\x05DELTA\x10\x01B\x0f\n" +
	"\r_left_stick_xB\x0f\n" +
	"\r_left_stick_yB\x10\n" +
	"\x0e_right_stick_xB\x10\n" +
	"\x0e_right_stick_yB\x0f\n" +
	"\r_left_triggerB\x10\n" +
	"\x0e_right_triggerB\t\n" +
	"\a_dpad_xB\t\n" +
	"\a_dpad_yB\x11\n" +
	"\x0f_changed_fields\"\xde\x01\n" +
	"\x13RTCIceCandidateInit\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12)\n" +
	"\rsdpMLineIndex\x18\x02 \x01(\rH\x00R\rsdpMLineIndex\x88\x01\x01\x12\x1b\n" +
	"\x06sdpMid\x18\x03 \x01(\tH\x01R\x06sdpMid\x88\x01\x01\x12/\n" +
	"\x10usernameFragment\x18\x04 \x01(\tH\x02R\x10usernameFragment\x88\x01\x01B\x10\n" +
	"\x0e_sdpMLineIndexB\t\n" +
	"\a_sdpMidB\x13\n" +
	"\x11_usernameFragment\"A\n" +
	"\x19RTCSessionDescriptionInit\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"D\n" +
	"\bProtoICE\x128\n" +
	"\tcandidate\x18\x01 \x01(\v2\x1a.proto.RTCIceCandidateInitR\tcandidate\">\n" +
	"\bProtoSDP\x122\n" +
	"\x03sdp\x18\x01 \x01(\v2 .proto.RTCSessionDescriptionInitR\x03sdp\"\x1e\n" +
	"\bProtoRaw\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"Z\n" +
	"\x1cProtoClientRequestRoomStream\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"c\n" +
	"\x17ProtoClientDisconnected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10controller_slots\x18\x02 \x03(\x05R\x0fcontrollerSlots\"4\n" +
	"\x15ProtoServerPushStream\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomNameB\x16Z\x14relay/internal/protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_types_proto_goTypes = []any{
	(ProtoControllerStateBatch_UpdateType)(0), // 0: proto.ProtoControllerStateBatch.UpdateType
	(*ProtoMouseMove)(nil),                    // 1: proto.ProtoMouseMove
	(*ProtoMouseMoveAbs)(nil),                 // 2: proto.ProtoMouseMoveAbs
	(*ProtoMouseWheel)(nil),                   // 3: proto.ProtoMouseWheel
	(*ProtoMouseKeyDown)(nil),                 // 4: proto.ProtoMouseKeyDown
	(*ProtoMouseKeyUp)(nil),                   // 5: proto.ProtoMouseKeyUp
	(*ProtoKeyDown)(nil),                      // 6: proto.ProtoKeyDown
	(*ProtoKeyUp)(nil),                        // 7: proto.ProtoKeyUp
	(*ProtoControllerAttach)(nil),             // 8: proto.ProtoControllerAttach
	(*ProtoControllerDetach)(nil),             // 9: proto.ProtoControllerDetach
	(*ProtoControllerRumble)(nil),             // 10: proto.ProtoControllerRumble
	(*ProtoControllerStateBatch)(nil),         // 11: proto.ProtoControllerStateBatch
	(*RTCIceCandidateInit)(nil),               // 12: proto.RTCIceCandidateInit
	(*RTCSessionDescriptionInit)(nil),         // 13: proto.RTCSessionDescriptionInit
	(*ProtoICE)(nil),                          // 14: proto.ProtoICE
	(*ProtoSDP)(nil),                          // 15: proto.ProtoSDP
	(*ProtoRaw)(nil),                          // 16: proto.ProtoRaw
	(*ProtoClientRequestRoomStream)(nil),      // 17: proto.ProtoClientRequestRoomStream
	(*ProtoClientDisconnected)(nil),           // 18: proto.ProtoClientDisconnected
	(*ProtoServerPushStream)(nil),             // 19: proto.ProtoServerPushStream
	nil,                                       // 20: proto.ProtoControllerStateBatch.ButtonChangedMaskEntry
}
var file_types_proto_depIdxs = []int32{
	0,  // 0: proto.ProtoControllerStateBatch.update_type:type_name -> proto.ProtoControllerStateBatch.UpdateType
	20, // 1: proto.ProtoControllerStateBatch.button_changed_mask:type_name -> proto.ProtoControllerStateBatch.ButtonChangedMaskEntry
	12, // 2: proto.ProtoICE.candidate:type_name -> proto.RTCIceCandidateInit
	13, // 3: proto.ProtoSDP.sdp:type_name -> proto.RTCSessionDescriptionInit
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	file_types_proto_msgTypes[10].OneofWrappers = []any{}
	file_types_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
