// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MouseMove message
type ProtoMouseMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseMove) Reset() {
	*x = ProtoMouseMove{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseMove) ProtoMessage() {}

func (x *ProtoMouseMove) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseMove.ProtoReflect.Descriptor instead.
func (*ProtoMouseMove) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMouseMove) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseMove) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseMoveAbs message
type ProtoMouseMoveAbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseMoveAbs) Reset() {
	*x = ProtoMouseMoveAbs{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseMoveAbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseMoveAbs) ProtoMessage() {}

func (x *ProtoMouseMoveAbs) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseMoveAbs.ProtoReflect.Descriptor instead.
func (*ProtoMouseMoveAbs) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoMouseMoveAbs) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseMoveAbs) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseWheel message
type ProtoMouseWheel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseWheel) Reset() {
	*x = ProtoMouseWheel{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseWheel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseWheel) ProtoMessage() {}

func (x *ProtoMouseWheel) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseWheel.ProtoReflect.Descriptor instead.
func (*ProtoMouseWheel) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoMouseWheel) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseWheel) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseKeyDown message
type ProtoMouseKeyDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseKeyDown) Reset() {
	*x = ProtoMouseKeyDown{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseKeyDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseKeyDown) ProtoMessage() {}

func (x *ProtoMouseKeyDown) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseKeyDown.ProtoReflect.Descriptor instead.
func (*ProtoMouseKeyDown) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoMouseKeyDown) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// MouseKeyUp message
type ProtoMouseKeyUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseKeyUp) Reset() {
	*x = ProtoMouseKeyUp{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseKeyUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseKeyUp) ProtoMessage() {}

func (x *ProtoMouseKeyUp) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseKeyUp.ProtoReflect.Descriptor instead.
func (*ProtoMouseKeyUp) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoMouseKeyUp) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// KeyDown message
type ProtoKeyDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoKeyDown) Reset() {
	*x = ProtoKeyDown{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoKeyDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoKeyDown) ProtoMessage() {}

func (x *ProtoKeyDown) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoKeyDown.ProtoReflect.Descriptor instead.
func (*ProtoKeyDown) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoKeyDown) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// KeyUp message
type ProtoKeyUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoKeyUp) Reset() {
	*x = ProtoKeyUp{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoKeyUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoKeyUp) ProtoMessage() {}

func (x *ProtoKeyUp) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoKeyUp.ProtoReflect.Descriptor instead.
func (*ProtoKeyUp) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoKeyUp) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// ControllerAttach message
type ProtoControllerAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                       // One of the following enums: "ps", "xbox" or "switch"
	SessionSlot   int32                  `protobuf:"varint,2,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerAttach) Reset() {
	*x = ProtoControllerAttach{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerAttach) ProtoMessage() {}

func (x *ProtoControllerAttach) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerAttach.ProtoReflect.Descriptor instead.
func (*ProtoControllerAttach) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoControllerAttach) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtoControllerAttach) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerAttach) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ControllerDetach message
type ProtoControllerDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerDetach) Reset() {
	*x = ProtoControllerDetach{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerDetach) ProtoMessage() {}

func (x *ProtoControllerDetach) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerDetach.ProtoReflect.Descriptor instead.
func (*ProtoControllerDetach) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *ProtoControllerDetach) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerDetach) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ControllerButton message
type ProtoControllerButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	Button        int32                  `protobuf:"varint,3,opt,name=button,proto3" json:"button,omitempty"`                              // Button code (linux input event code)
	Pressed       bool                   `protobuf:"varint,4,opt,name=pressed,proto3" json:"pressed,omitempty"`                            // true if pressed, false if released
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerButton) Reset() {
	*x = ProtoControllerButton{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerButton) ProtoMessage() {}

func (x *ProtoControllerButton) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerButton.ProtoReflect.Descriptor instead.
func (*ProtoControllerButton) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *ProtoControllerButton) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerButton) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoControllerButton) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *ProtoControllerButton) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

// ControllerTriggers message
type ProtoControllerTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	Trigger       int32                  `protobuf:"varint,3,opt,name=trigger,proto3" json:"trigger,omitempty"`                            // Trigger number (0 for left, 1 for right)
	Value         int32                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`                                // trigger value (-32768 to 32767)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerTrigger) Reset() {
	*x = ProtoControllerTrigger{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerTrigger) ProtoMessage() {}

func (x *ProtoControllerTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerTrigger.ProtoReflect.Descriptor instead.
func (*ProtoControllerTrigger) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *ProtoControllerTrigger) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerTrigger) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoControllerTrigger) GetTrigger() int32 {
	if x != nil {
		return x.Trigger
	}
	return 0
}

func (x *ProtoControllerTrigger) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ControllerSticks message
type ProtoControllerStick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	Stick         int32                  `protobuf:"varint,3,opt,name=stick,proto3" json:"stick,omitempty"`                                // Stick number (0 for left, 1 for right)
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`                                        // X axis value (-32768 to 32767)
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`                                        // Y axis value (-32768 to 32767)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerStick) Reset() {
	*x = ProtoControllerStick{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerStick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerStick) ProtoMessage() {}

func (x *ProtoControllerStick) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerStick.ProtoReflect.Descriptor instead.
func (*ProtoControllerStick) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

func (x *ProtoControllerStick) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerStick) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoControllerStick) GetStick() int32 {
	if x != nil {
		return x.Stick
	}
	return 0
}

func (x *ProtoControllerStick) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoControllerStick) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// ControllerAxis message
type ProtoControllerAxis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"` // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // Session ID of the client
	Axis          int32                  `protobuf:"varint,3,opt,name=axis,proto3" json:"axis,omitempty"`                                  // Axis number (0 for d-pad horizontal, 1 for d-pad vertical)
	Value         int32                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`                                // axis value (-1 to 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerAxis) Reset() {
	*x = ProtoControllerAxis{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerAxis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerAxis) ProtoMessage() {}

func (x *ProtoControllerAxis) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerAxis.ProtoReflect.Descriptor instead.
func (*ProtoControllerAxis) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

func (x *ProtoControllerAxis) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerAxis) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoControllerAxis) GetAxis() int32 {
	if x != nil {
		return x.Axis
	}
	return 0
}

func (x *ProtoControllerAxis) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ControllerRumble message
type ProtoControllerRumble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionSlot   int32                  `protobuf:"varint,1,opt,name=session_slot,json=sessionSlot,proto3" json:"session_slot,omitempty"`       // Session specific slot number (0-3)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // Session ID of the client
	LowFrequency  int32                  `protobuf:"varint,3,opt,name=low_frequency,json=lowFrequency,proto3" json:"low_frequency,omitempty"`    // Low frequency rumble (0-65535)
	HighFrequency int32                  `protobuf:"varint,4,opt,name=high_frequency,json=highFrequency,proto3" json:"high_frequency,omitempty"` // High frequency rumble (0-65535)
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                                // Duration in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoControllerRumble) Reset() {
	*x = ProtoControllerRumble{}
	mi := &file_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoControllerRumble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoControllerRumble) ProtoMessage() {}

func (x *ProtoControllerRumble) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoControllerRumble.ProtoReflect.Descriptor instead.
func (*ProtoControllerRumble) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{13}
}

func (x *ProtoControllerRumble) GetSessionSlot() int32 {
	if x != nil {
		return x.SessionSlot
	}
	return 0
}

func (x *ProtoControllerRumble) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoControllerRumble) GetLowFrequency() int32 {
	if x != nil {
		return x.LowFrequency
	}
	return 0
}

func (x *ProtoControllerRumble) GetHighFrequency() int32 {
	if x != nil {
		return x.HighFrequency
	}
	return 0
}

func (x *ProtoControllerRumble) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type RTCIceCandidateInit struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMLineIndex    *uint32                `protobuf:"varint,2,opt,name=sdpMLineIndex,proto3,oneof" json:"sdpMLineIndex,omitempty"`
	SdpMid           *string                `protobuf:"bytes,3,opt,name=sdpMid,proto3,oneof" json:"sdpMid,omitempty"`
	UsernameFragment *string                `protobuf:"bytes,4,opt,name=usernameFragment,proto3,oneof" json:"usernameFragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RTCIceCandidateInit) Reset() {
	*x = RTCIceCandidateInit{}
	mi := &file_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTCIceCandidateInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTCIceCandidateInit) ProtoMessage() {}

func (x *RTCIceCandidateInit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTCIceCandidateInit.ProtoReflect.Descriptor instead.
func (*RTCIceCandidateInit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{14}
}

func (x *RTCIceCandidateInit) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *RTCIceCandidateInit) GetSdpMLineIndex() uint32 {
	if x != nil && x.SdpMLineIndex != nil {
		return *x.SdpMLineIndex
	}
	return 0
}

func (x *RTCIceCandidateInit) GetSdpMid() string {
	if x != nil && x.SdpMid != nil {
		return *x.SdpMid
	}
	return ""
}

func (x *RTCIceCandidateInit) GetUsernameFragment() string {
	if x != nil && x.UsernameFragment != nil {
		return *x.UsernameFragment
	}
	return ""
}

type RTCSessionDescriptionInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTCSessionDescriptionInit) Reset() {
	*x = RTCSessionDescriptionInit{}
	mi := &file_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTCSessionDescriptionInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTCSessionDescriptionInit) ProtoMessage() {}

func (x *RTCSessionDescriptionInit) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTCSessionDescriptionInit.ProtoReflect.Descriptor instead.
func (*RTCSessionDescriptionInit) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{15}
}

func (x *RTCSessionDescriptionInit) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *RTCSessionDescriptionInit) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ProtoICE message
type ProtoICE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     *RTCIceCandidateInit   `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoICE) Reset() {
	*x = ProtoICE{}
	mi := &file_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoICE) ProtoMessage() {}

func (x *ProtoICE) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoICE.ProtoReflect.Descriptor instead.
func (*ProtoICE) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{16}
}

func (x *ProtoICE) GetCandidate() *RTCIceCandidateInit {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// ProtoSDP message
type ProtoSDP struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sdp           *RTCSessionDescriptionInit `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSDP) Reset() {
	*x = ProtoSDP{}
	mi := &file_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSDP) ProtoMessage() {}

func (x *ProtoSDP) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSDP.ProtoReflect.Descriptor instead.
func (*ProtoSDP) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{17}
}

func (x *ProtoSDP) GetSdp() *RTCSessionDescriptionInit {
	if x != nil {
		return x.Sdp
	}
	return nil
}

// ProtoRaw message
type ProtoRaw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoRaw) Reset() {
	*x = ProtoRaw{}
	mi := &file_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoRaw) ProtoMessage() {}

func (x *ProtoRaw) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoRaw.ProtoReflect.Descriptor instead.
func (*ProtoRaw) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{18}
}

func (x *ProtoRaw) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// ProtoClientRequestRoomStream message
type ProtoClientRequestRoomStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoClientRequestRoomStream) Reset() {
	*x = ProtoClientRequestRoomStream{}
	mi := &file_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoClientRequestRoomStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoClientRequestRoomStream) ProtoMessage() {}

func (x *ProtoClientRequestRoomStream) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoClientRequestRoomStream.ProtoReflect.Descriptor instead.
func (*ProtoClientRequestRoomStream) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{19}
}

func (x *ProtoClientRequestRoomStream) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ProtoClientRequestRoomStream) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ProtoClientDisconnected message
type ProtoClientDisconnected struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ControllerSlots []int32                `protobuf:"varint,2,rep,packed,name=controller_slots,json=controllerSlots,proto3" json:"controller_slots,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProtoClientDisconnected) Reset() {
	*x = ProtoClientDisconnected{}
	mi := &file_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoClientDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoClientDisconnected) ProtoMessage() {}

func (x *ProtoClientDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoClientDisconnected.ProtoReflect.Descriptor instead.
func (*ProtoClientDisconnected) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{20}
}

func (x *ProtoClientDisconnected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoClientDisconnected) GetControllerSlots() []int32 {
	if x != nil {
		return x.ControllerSlots
	}
	return nil
}

// ProtoServerPushStream message
type ProtoServerPushStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoServerPushStream) Reset() {
	*x = ProtoServerPushStream{}
	mi := &file_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoServerPushStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoServerPushStream) ProtoMessage() {}

func (x *ProtoServerPushStream) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoServerPushStream.ProtoReflect.Descriptor instead.
func (*ProtoServerPushStream) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{21}
}

func (x *ProtoServerPushStream) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05proto\",\n" +
	"\x0eProtoMouseMove\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"/\n" +
	"\x11ProtoMouseMoveAbs\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"-\n" +
	"\x0fProtoMouseWheel\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"%\n" +
	"\x11ProtoMouseKeyDown\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\"#\n" +
	"\x0fProtoMouseKeyUp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\" \n" +
	"\fProtoKeyDown\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\"\x1e\n" +
	"\n" +
	"ProtoKeyUp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\"i\n" +
	"\x15ProtoControllerAttach\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fsession_slot\x18\x02 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"Y\n" +
	"\x15ProtoControllerDetach\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x8b\x01\n" +
	"\x15ProtoControllerButton\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06button\x18\x03 \x01(\x05R\x06button\x12\x18\n" +
	"\apressed\x18\x04 \x01(\bR\apressed\"\x8a\x01\n" +
	"\x16ProtoControllerTrigger\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\x05R\atrigger\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value\"\x8a\x01\n" +
	"\x14ProtoControllerStick\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05stick\x18\x03 \x01(\x05R\x05stick\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\"\x81\x01\n" +
	"\x13ProtoControllerAxis\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04axis\x18\x03 \x01(\x05R\x04axis\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value\"\xc1\x01\n" +
	"\x15ProtoControllerRumble\x12!\n" +
	"\fsession_slot\x18\x01 \x01(\x05R\vsessionSlot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rlow_frequency\x18\x03 \x01(\x05R\flowFrequency\x12%\n" +
	"\x0ehigh_frequency\x18\x04 \x01(\x05R\rhighFrequency\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\"\xde\x01\n" +
	"\x13RTCIceCandidateInit\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12)\n" +
	"\rsdpMLineIndex\x18\x02 \x01(\rH\x00R\rsdpMLineIndex\x88\x01\x01\x12\x1b\n" +
	"\x06sdpMid\x18\x03 \x01(\tH\x01R\x06sdpMid\x88\x01\x01\x12/\n" +
	"\x10usernameFragment\x18\x04 \x01(\tH\x02R\x10usernameFragment\x88\x01\x01B\x10\n" +
	"\x0e_sdpMLineIndexB\t\n" +
	"\a_sdpMidB\x13\n" +
	"\x11_usernameFragment\"A\n" +
	"\x19RTCSessionDescriptionInit\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"D\n" +
	"\bProtoICE\x128\n" +
	"\tcandidate\x18\x01 \x01(\v2\x1a.proto.RTCIceCandidateInitR\tcandidate\">\n" +
	"\bProtoSDP\x122\n" +
	"\x03sdp\x18\x01 \x01(\v2 .proto.RTCSessionDescriptionInitR\x03sdp\"\x1e\n" +
	"\bProtoRaw\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"Z\n" +
	"\x1cProtoClientRequestRoomStream\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"c\n" +
	"\x17ProtoClientDisconnected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10controller_slots\x18\x02 \x03(\x05R\x0fcontrollerSlots\"4\n" +
	"\x15ProtoServerPushStream\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomNameB\x16Z\x14relay/internal/protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_types_proto_goTypes = []any{
	(*ProtoMouseMove)(nil),               // 0: proto.ProtoMouseMove
	(*ProtoMouseMoveAbs)(nil),            // 1: proto.ProtoMouseMoveAbs
	(*ProtoMouseWheel)(nil),              // 2: proto.ProtoMouseWheel
	(*ProtoMouseKeyDown)(nil),            // 3: proto.ProtoMouseKeyDown
	(*ProtoMouseKeyUp)(nil),              // 4: proto.ProtoMouseKeyUp
	(*ProtoKeyDown)(nil),                 // 5: proto.ProtoKeyDown
	(*ProtoKeyUp)(nil),                   // 6: proto.ProtoKeyUp
	(*ProtoControllerAttach)(nil),        // 7: proto.ProtoControllerAttach
	(*ProtoControllerDetach)(nil),        // 8: proto.ProtoControllerDetach
	(*ProtoControllerButton)(nil),        // 9: proto.ProtoControllerButton
	(*ProtoControllerTrigger)(nil),       // 10: proto.ProtoControllerTrigger
	(*ProtoControllerStick)(nil),         // 11: proto.ProtoControllerStick
	(*ProtoControllerAxis)(nil),          // 12: proto.ProtoControllerAxis
	(*ProtoControllerRumble)(nil),        // 13: proto.ProtoControllerRumble
	(*RTCIceCandidateInit)(nil),          // 14: proto.RTCIceCandidateInit
	(*RTCSessionDescriptionInit)(nil),    // 15: proto.RTCSessionDescriptionInit
	(*ProtoICE)(nil),                     // 16: proto.ProtoICE
	(*ProtoSDP)(nil),                     // 17: proto.ProtoSDP
	(*ProtoRaw)(nil),                     // 18: proto.ProtoRaw
	(*ProtoClientRequestRoomStream)(nil), // 19: proto.ProtoClientRequestRoomStream
	(*ProtoClientDisconnected)(nil),      // 20: proto.ProtoClientDisconnected
	(*ProtoServerPushStream)(nil),        // 21: proto.ProtoServerPushStream
}
var file_types_proto_depIdxs = []int32{
	14, // 0: proto.ProtoICE.candidate:type_name -> proto.RTCIceCandidateInit
	15, // 1: proto.ProtoSDP.sdp:type_name -> proto.RTCSessionDescriptionInit
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	file_types_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
