[package]
name = "nestri-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nestri-server"
path = "src/main.rs"

[dependencies]
gst.workspace = true
gst-app.workspace = true
serde = {version = "1.0.214", features = ["derive"] }
tokio = { version = "1.41.0", features = ["full"] }
clap = { version = "4.5.20", features = ["env"] }
serde_json = "1.0.132"
webrtc = "0.11.0"
reqwest = { version = "0.12", features = ["json"] }
regex = "1.11.1"
rand = "0.8.5"
rustls = { version = "0.23.17", features = ["ring"] }
