[package]
name = "nestri-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nestri-server"
path = "src/main.rs"

[dependencies]
gst.workspace = true
gst-webrtc.workspace = true
gstrswebrtc.workspace = true
serde = {version = "1.0.214", features = ["derive"] }
tokio = { version = "1.41.0", features = ["full"] }
clap = { version = "4.5.20", features = ["env"] }
serde_json = "1.0.132"
webrtc = "0.11.0"
regex = "1.11.1"
rand = "0.8.5"
rustls = { version = "0.23.17", features = ["ring"] }
tokio-util = "0.7.12"
flate2 = "1.0.35"
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
log = { version = "0.4.22", features = ["std"] }
chrono = "0.4.38"
futures-util = "0.3.31"
num-derive = "0.4.2"
num-traits = "0.2.19"
