[package]
name = "nestri-server"
version = "0.1.0-alpha.2"
edition = "2024"

[[bin]]
name = "nestri-server"
path = "src/main.rs"

[dependencies]
gstreamer = { version = "0.23", features = ["v1_26"] }
gstreamer-webrtc = { version = "0.23", features = ["v1_26"] }
gst-plugin-webrtc = { version = "0.13", features = ["v1_22"] }
serde = {version = "1.0", features = ["derive"] }
tokio = { version = "1.45", features = ["full"] }
tokio-stream = { version = "0.1", features = ["full"] }
clap = { version = "4.5", features = ["env", "derive"] }
serde_json = "1.0"
webrtc = "0.13"
regex = "1.11"
rand = "0.9"
rustls = { version = "0.23", features = ["ring"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4"
prost = "0.14"
prost-types = "0.14"
parking_lot = "0.12"
atomic_refcell = "0.1"
byteorder = "1.5"
libp2p = { version = "0.55", features = ["identify", "dns", "tcp", "noise", "ping", "tokio", "serde", "yamux", "macros", "websocket", "autonat"] }
libp2p-stream = { version = "0.3.0-alpha" }
dashmap = "6.1"
