[package]
name = "nestri-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nestri-server"
path = "src/main.rs"

[dependencies]
gst = { package = "gstreamer", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", version = "0.24.0" }
moq-gst = { git = "https://github.com/wanjohiryan/moq-gst", branch = "main" }
tokio = { version = "1.41.0", features = ["full"] }
serde = {version = "1.0.214", features = ["derive"] }
tracing-subscriber = "0.3"
futures-util = "0.3.31"
serde_json = "1.0.132"
actix-web = "4.9.0"
tracing = "0.1.40"
actix-ws = "0.3.0"
regex = "1.11.1"
clap = { version = "4.5.20", features = ["env"] }
rand = "0.8.5"
