/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Auth": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AuthFingerprintKey": {
      "type": "random.index/randomString.RandomString"
      "value": string
    }
    "CloudflareAuthKV": {
      "type": "sst.cloudflare.Kv"
    }
    "InstantAdminToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InstantAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LoopsApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
