/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "AuthFingerprintKey": {
      "type": "random.index/randomString.RandomString"
      "value": string
    }
    "InstantAdminToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InstantAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LoopsApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "Auth": cloudflare.Service
    "CloudflareAuthKV": cloudflare.KVNamespace
  }
}
