#Tabs not spaces, you moron :)

name: Build nestri:relay
on:
    pull_request:
        paths:
            - "containers/relay.Containerfile"
            - "packages/relay/**"
            - ".github/workflows/relay.yml"
    schedule:
        - cron: 0 0 * * * # At the end of everyday to keep that build cache warm
    push:
        branches: [main]
        paths:
            - "containers/relay.Containerfile"
            - ".github/workflows/relay.yml"
            - "packages/relay/**"
        tags:
            - v*.*.*
    release:
        types: [created]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: nestrilabs/nestri
    BASE_TAG_PREFIX: relay

jobs:
    build-docker-pr:
        name: Build image on PR
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - 
              name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                file: containers/relay.Containerfile
                context: ./
                push: false
                load: true
                tags: nestri:relay
    
    build-docker-main:
        name: Build image on main
        if: ${{  github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ github.token }}
            - 
              name: Extract Container metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.BASE_TAG_PREFIX }}
                #
                #tag on release, and a nightly build for 'dev'
                tags: |
                  type=raw,value=nightly,enable={{is_default_branch}}
                  type=ref,event=tag
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
            - 
              name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                file:  containers/relay.Containerfile
                context: ./
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}