#Tabs not spaces, you moron :)

name: Build nestri:runner

on:
    pull_request:
        paths:
            - "containers/runner.Containerfile"
            - "packages/scripts/**"
            - "packages/server/**"
            - ".github/workflows/runner.yml"
    schedule:
        - cron: 7 0 * * 1,3,6 # Regularly to keep that build cache warm
    push:
        branches: [main]
        paths:
            - "containers/runner.Containerfile"
            - ".github/workflows/runner.yml"
            - "packages/scripts/**"
            - "packages/server/**"
        tags:
            - v*.*.*
    release:
        types: [created]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: nestrilabs/nestri
    BASE_TAG_PREFIX: runner
    BASE_IMAGE: docker.io/cachyos/cachyos:latest

# This makes our release ci quit prematurely
# concurrency:
#     group: ci-${{ github.ref }}
#     cancel-in-progress: true

jobs:
    build-docker-pr:
        name: Build image on PR
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - 
              name: Set Swap Space
              uses: pierotofy/set-swap-space@master
              with:
                swap-size-gb: 20
            - 
              name: Build Docker image
              uses: docker/build-push-action@v6
              with:
                file: containers/runner.Containerfile
                context: ./
                push: false
                load: true
                tags: nestri:runner
                cache-from: type=gha,mode=max
                cache-to: type=gha,mode=max

    build-docker-main:
        name: Build image on main
        if: ${{  github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ github.token }}
            - 
              name: Extract Container metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.BASE_TAG_PREFIX }}
                #
                #tag on release, and a nightly build for 'dev'
                tags: |
                  type=raw,value=nightly,enable={{is_default_branch}}
                  type=ref,event=tag
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
            - 
              name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - 
              name: Set Swap Space
              uses: pierotofy/set-swap-space@master
              with:
                swap-size-gb: 20
            - 
              name: Build Docker image
              uses: docker/build-push-action@v6
              with:
                file:  containers/runner.Containerfile
                context: ./
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha,mode=max
                cache-to: type=gha,mode=max
                pull: ${{ github.event_name == 'schedule' }} # Pull base image for scheduled builds
